### ISSUE TITLE
Cannot generate New-SpotifyAccesToken

### ISSUE THREAD

**Issue by dimitri-dg** [lennyomg/Spotify-PowerShell#2]
Hello there,

being fairly new in the PowerShell-world, I experienced some issues trying to set up this 'Spotify-PowerShell' module.

Following the steps to your module, I came across an error message. Entering the 'New-SpotifyAccessToken' command after doing the preceding steps gives me an error telling me the command is not found in the module Spotify. Then it recommends me to use the command 'Import-Module Spotify' which gives me other errors.

Do you have an idea what might cause these errors?

Thanks in advance.

Dimitri

![MicrosoftTeams-image](https://github.com/lennyomg/Spotify-PowerShell/assets/145262408/0a729888-638e-44fe-87ce-2e33017e7e86)

**Comment by lennyomg** [comment]
Use PowerShell 7
https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.4

The version that comes with Windows is 5.xx and it doesn't support some new syntax.
